services:
  redis:
    image: redis:7-bookworm
    restart: always
    volumes:
      - ./data:/data
      - ./data/redis.conf:/data/redis.conf
    command: redis-server /data/redis.conf --loglevel notice --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379" # En la izquierda el de docker y en la derecha el de redis
    networks:
      - mired

networks:
    mired: