version: '3.3'
services:
  postgresql: # Es único, se puede poner cualquier nombre pero no se puede repetir.
    container_name: postgresql-servidor # Este es opcional. Pero no se puede repetir con otras imágenes.
    image: postgres:16

    networks:
      - mired
    # command: para agregar parámetros al iniciar el contenedor.
    ports:
      - '5433:5432' # En la izquierda el de docker y en la derecha el de postgress
    environment:
      - POSTGRES_PASSWORD=${PASS_DB}
      - POSTGRES_DB=${NAME_DB}
      - POSTGRES_USER=${USER_DB}
      - PGDATA=/var/lib/postgresql/data
    volumes: # Es lo que vincula es host con el contenedor. Es lo que vincula los datos de la "RAM" y los persiste en el disco.
      # Es buena práctica path relativo desde el proyecto ./_data:/lib/postgresql.
      - ./_data:/var/lib/postgresql
    restart: always # Para que se ejecute cada vez que arranca Docker.

networks:
  mired:
