services:
    armeria-product:
    #container_name: micro1  no tiene que estar porque no se puede escalar
        image: msproduct:v1.0.2
        networks:
            mired:
                aliases: #Es para cuando quiera encontrar a un microservicio que se ejecute. Le agrego un nombre a una ip
                    - "armeria-product.um.localhost"
        environment:
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_DB=${REDIS_DB} #El nombre es 0 por defecto
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - USER_DB=${USER_DB}
            - PASS_DB=${PASS_DB}
            - URL_DB=${URL_DB}
            - PORT_DB=${PORT_DB}
            - NAME_DB=${NAME_DB}
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.armeria-product.rule=Host(`armeria-product.um.localhost`)"
            - "traefik.http.routers.armeria-product.tls=true"
            - "traefik.http.services.armeria-product.loadbalancer.server.port=5000"
            - "traefik.docker.network=mired"
            - "traefik.http.middlewares.armeria-product.circuitbreaker.expression=LatencyAtQuantileMS(50.0) > 100"
            - "traefik.http.middlewares.armeria-product.circuitbreaker.expression=ResponseCodeRatio(500, 600, 0, 600) > 0.25"
            - "traefik.http.middlewares.armeria-product.circuitbreaker.expression=NetworkErrorRatio() > 0.5"
networks:
    mired:
        external: true #Si no salta un error, tengo que crear la red -> docker network create <nombre del a red (en este caso mired)> 